using System.Windows;
using System.Windows.Media;
using H.NotifyIcon;

namespace GameDeck.App.Tray;

/// <summary>Placeholder tray icon: ♪ on a dark rounded tile, generated by H.NotifyIcon.</summary>
public static class TrayIconFactory
{
    public static void ApplyGeneratedIcon(TaskbarIcon icon)
    {
        icon.IconSource = new GeneratedIconSource
        {
            Text = "♪",
            Foreground = Brushes.White,
            Background = new SolidColorBrush(Color.FromRgb(0x1E, 0x1E, 0x2A)),
            FontWeight = FontWeights.Bold,
            CornerRadius = new CornerRadius(28),
        };
    }
}
